# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: git clone https://github.com/flutter/flutter.git -b beta
  displayName: 'Install Flutter'

- script: ./flutter/bin/flutter doctor
  displayName: 'Flutter Doctor'

- script: ./flutter/bin/flutter test
  displayName: 'Flutter Test'
